extends Node
signal code_to_make();
signal go_forward(steps);
signal go_right(steps);
signal go_left(steps);
signal restart_button();
signal scratch(value);
signal changed_needs();
signal set_player_pos(position);
